import {AuthProvider} from '@/contexts'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="kr">
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
